source "https://rubygems.org"

gem 'eventmachine',     '~> 0.12.10'
gem 'em-hiredis',       '~> 0.1.0'
gem 'em-websocket'
gem 'rack',             '~> 1.5'
gem 'rack-fiber_pool',  '~> 0.9.2'
gem 'signature',        '~> 0.1.6'
gem 'activesupport',    '~> 3.1'
gem 'glamazon',         '~> 0.3.1'
gem 'sinatra',          '~> 1.2.6'
gem 'em-http-request',  '~> 0.3.0'
gem 'pry'